# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ancfcc_test
                                 A QGIS plugin
 this is an experimental test version of this plugin
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-02-04
        copyright            : (C) 2020 by Ancfcc
        email                : ilyasbenhssine@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ancfcc_test class from file ancfcc_test.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .anfcc_test import ancfcc_test
    return ancfcc_test(iface)
