# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'anfcc_test_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Ancfcc(object):
    def setupUi(self, Ancfcc):
        Ancfcc.setObjectName("Ancfcc")
        Ancfcc.resize(472, 632)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Ancfcc.setWindowIcon(icon)
        self.verticalLayoutWidget = QtWidgets.QWidget(Ancfcc)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 0, 431, 361))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.comboBoxNature = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBoxNature.setObjectName("comboBoxNature")
        self.verticalLayout.addWidget(self.comboBoxNature)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.lineEditNum = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEditNum.setObjectName("lineEditNum")
        self.verticalLayout.addWidget(self.lineEditNum)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.lineEditIndice = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEditIndice.setObjectName("lineEditIndice")
        self.verticalLayout.addWidget(self.lineEditIndice)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.mQgsProjectionSelectionWidget = QgsProjectionSelectionWidget(self.verticalLayoutWidget)
        self.mQgsProjectionSelectionWidget.setObjectName("mQgsProjectionSelectionWidget")
        self.verticalLayout.addWidget(self.mQgsProjectionSelectionWidget)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.comboBoxType = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBoxType.setObjectName("comboBoxType")
        self.verticalLayout.addWidget(self.comboBoxType)
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.spinBoxnb_bornes = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.spinBoxnb_bornes.setObjectName("spinBoxnb_bornes")
        self.verticalLayout.addWidget(self.spinBoxnb_bornes)
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.comboBoxMap = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBoxMap.setObjectName("comboBoxMap")
        self.verticalLayout.addWidget(self.comboBoxMap)
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.lineEditSurface = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEditSurface.setEnabled(False)
        self.lineEditSurface.setObjectName("lineEditSurface")
        self.verticalLayout.addWidget(self.lineEditSurface)
        self.label_9 = QtWidgets.QLabel(Ancfcc)
        self.label_9.setGeometry(QtCore.QRect(20, 370, 429, 14))
        self.label_9.setObjectName("label_9")
        self.UpButton = QtWidgets.QPushButton(Ancfcc)
        self.UpButton.setGeometry(QtCore.QRect(430, 390, 21, 23))
        self.UpButton.setObjectName("UpButton")
        self.BottomButton = QtWidgets.QPushButton(Ancfcc)
        self.BottomButton.setGeometry(QtCore.QRect(430, 530, 21, 23))
        self.BottomButton.setObjectName("BottomButton")
        self.AddButton = QtWidgets.QPushButton(Ancfcc)
        self.AddButton.setGeometry(QtCore.QRect(20, 560, 31, 23))
        self.AddButton.setObjectName("AddButton")
        self.DeleteButton = QtWidgets.QPushButton(Ancfcc)
        self.DeleteButton.setGeometry(QtCore.QRect(60, 560, 31, 23))
        self.DeleteButton.setObjectName("DeleteButton")
        self.EditButton = QtWidgets.QPushButton(Ancfcc)
        self.EditButton.setGeometry(QtCore.QRect(100, 560, 75, 23))
        self.EditButton.setObjectName("EditButton")
        self.accept = QtWidgets.QPushButton(Ancfcc)
        self.accept.setGeometry(QtCore.QRect(350, 580, 101, 41))
        self.accept.setObjectName("accept")
        self.reject = QtWidgets.QPushButton(Ancfcc)
        self.reject.setGeometry(QtCore.QRect(240, 580, 101, 41))
        self.reject.setObjectName("reject")
        self.ErrorLabel = QtWidgets.QLabel(Ancfcc)
        self.ErrorLabel.setGeometry(QtCore.QRect(20, 600, 161, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ErrorLabel.setFont(font)
        self.ErrorLabel.setText("")
        self.ErrorLabel.setObjectName("ErrorLabel")
        self.tableWidgetBornes = QtWidgets.QTableWidget(Ancfcc)
        self.tableWidgetBornes.setGeometry(QtCore.QRect(20, 390, 401, 161))
        self.tableWidgetBornes.setObjectName("tableWidgetBornes")
        self.tableWidgetBornes.setColumnCount(3)
        self.tableWidgetBornes.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetBornes.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetBornes.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetBornes.setHorizontalHeaderItem(2, item)

        self.retranslateUi(Ancfcc)
        QtCore.QMetaObject.connectSlotsByName(Ancfcc)

    def retranslateUi(self, Ancfcc):
        _translate = QtCore.QCoreApplication.translate
        Ancfcc.setWindowTitle(_translate("Ancfcc", "Ancfcc Plugin"))
        self.label.setText(_translate("Ancfcc", "Nature"))
        self.label_2.setText(_translate("Ancfcc", "Num"))
        self.label_3.setText(_translate("Ancfcc", "Indice"))
        self.label_4.setText(_translate("Ancfcc", "Select Projection"))
        self.label_5.setText(_translate("Ancfcc", "Type"))
        self.label_6.setText(_translate("Ancfcc", "nb_bornes"))
        self.label_7.setText(_translate("Ancfcc", "Map"))
        self.label_8.setText(_translate("Ancfcc", "Surface"))
        self.label_9.setText(_translate("Ancfcc", "Bornes"))
        self.UpButton.setText(_translate("Ancfcc", "▲"))
        self.BottomButton.setText(_translate("Ancfcc", "▼"))
        self.AddButton.setText(_translate("Ancfcc", "+"))
        self.DeleteButton.setText(_translate("Ancfcc", "-"))
        self.EditButton.setText(_translate("Ancfcc", "Modifier"))
        self.accept.setText(_translate("Ancfcc", "Save"))
        self.reject.setText(_translate("Ancfcc", "Cancel"))
        item = self.tableWidgetBornes.horizontalHeaderItem(0)
        item.setText(_translate("Ancfcc", "Nom"))
        item = self.tableWidgetBornes.horizontalHeaderItem(1)
        item.setText(_translate("Ancfcc", "X"))
        item = self.tableWidgetBornes.horizontalHeaderItem(2)
        item.setText(_translate("Ancfcc", "Y"))

from qgsprojectionselectionwidget import QgsProjectionSelectionWidget
